name: CI Kaizen

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rendre le script exécutable
        run: chmod +x script.sh
      - name: Run script
        run: ./script.sh
        
  docker-build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository }}/bsimus:latest .

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}/bsimus:latest
  
  deploy-staging:
    needs: docker-build    
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment:
    name: staging
    steps:
      - name: Simuler déploiement staging
        run: echo "Déploiement en staging réussi"
  
  deploy-production:
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
    name: production
    steps:
      - name: Déploiement production
        run: echo "Déploiement en production" 
        
      
