name: CI/CD Pipeline
on:
  push
    branches:
      - main
jobs:
  build-and-push:
    runs-on: Ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@V4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository }}/app:latest .
      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}/app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Déploiement simulé
        run: echo "Déploiement automatique réussi"

